// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hello = { v: number, role: Role, guestId: string, displayName: string | null, adminToken: string | null, };

export type Role = "host" | "guest";

export type Welcome = { v: number, ts: bigint, seq: bigint, you: You, };

export type You = { clientId: string, role: Role, };
