// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Board = { id: string, kind: BoardKind, title: string, createdAt: bigint, ord: number, };

export type BoardKind = "pen" | "excalidraw";

export type ClientMsg = { "type": "Hello", v: number, id: string | null, role: Role, guestId: string, displayName: string | null, adminToken: string | null, } | { "type": "SetDisplayName", v: number, id: string | null, name: string, } | { "type": "GetSnapshot", v: number, id: string | null, since: bigint | null, } | { "type": "Pong", v: number, id: string | null, } | { "type": "AddTopic", v: number, id: string | null, parentId: string | null, title: string, afterId: string | null, } | { "type": "RenameTopic", v: number, id: string | null, topicId: string, title: string, } | { "type": "MoveTopic", v: number, id: string | null, topicId: string, newParentId: string | null, afterId: string | null, } | { "type": "DeleteTopic", v: number, id: string | null, topicId: string, } | { "type": "SetActiveTopic", v: number, id: string | null, topicId: string | null, } | { "type": "MarkTopicDone", v: number, id: string | null, topicId: string, done: boolean, } | { "type": "SubmitQuestion", v: number, id: string | null, text: string, anonymous: boolean, } | { "type": "VoteQuestion", v: number, id: string | null, questionId: string, vote: boolean, } | { "type": "MarkQuestionAnswered", v: number, id: string | null, questionId: string, answered: boolean, } | { "type": "DeleteQuestion", v: number, id: string | null, questionId: string, } | { "type": "CreateBoard", v: number, id: string | null, kind: BoardKind, title: string | null, } | { "type": "RenameBoard", v: number, id: string | null, boardId: string, title: string, } | { "type": "DeleteBoard", v: number, id: string | null, boardId: string, } | { "type": "SetFocusedBoard", v: number, id: string | null, boardId: string, } | { "type": "ExcalidrawUpdate", v: number, id: string | null, boardId: string, sceneVersion: bigint, elements: unknown[], appState: unknown, };

export type Guest = { guestId: string, displayName: string, muted: boolean, joinedAt: bigint, };

export type Presence = { guestId: string, displayName: string, muted: boolean, joinedAt: bigint, clientIds: Array<string>, };

export type Question = { id: string, roomId: string, authorGuestId: string, authorName: string, anonymous: boolean, text: string, answered: boolean, createdAt: bigint, voteCount: number, };

export type Role = "host" | "guest";

/**
 * Welcome snapshot delivered on Hello + on every GetSnapshot. M1 carries
 * only the always-present fields; later phases populate topics/boards/etc.
 */
export type RoomSnapshot = { room: RoomSummary, you: You, guests: Array<Guest>, presence: Array<Presence>, topics: Array<Topic>, activeTopicId: string | null, questions: Array<Question>, myVotes: Array<string>, boards: unknown[], focusedBoardId: string | null, hands: unknown[], seq: bigint, };

export type RoomSummary = { id: string, title: string, createdAt: bigint, };

export type ServerMsg = { "type": "Welcome", v: number, ts: bigint, seq: bigint, you: You, snapshot: RoomSnapshot, } | { "type": "Error", v: number, ts: bigint, seq: bigint, code: string, message: string, refId: string | null, } | { "type": "Ack", v: number, ts: bigint, seq: bigint, refId: string, } | { "type": "PresenceUpdate", v: number, ts: bigint, seq: bigint, guests: Array<Guest>, } | { "type": "RoomSnapshot", v: number, ts: bigint, seq: bigint, snapshot: RoomSnapshot, } | { "type": "Ping", v: number, ts: bigint, seq: bigint, } | { "type": "TopicTreeUpdated", v: number, ts: bigint, seq: bigint, topics: Array<Topic>, activeTopicId: string | null, } | { "type": "QuestionAdded", v: number, ts: bigint, seq: bigint, question: Question, } | { "type": "QuestionUpdated", v: number, ts: bigint, seq: bigint, question: Question, } | { "type": "QuestionDeleted", v: number, ts: bigint, seq: bigint, questionId: string, } | { "type": "VoteUpdated", v: number, ts: bigint, seq: bigint, questionId: string, voteCount: number, voterGuestId: string, } | { "type": "BoardCreated", v: number, ts: bigint, seq: bigint, board: Board, } | { "type": "BoardUpdated", v: number, ts: bigint, seq: bigint, board: Board, } | { "type": "BoardDeleted", v: number, ts: bigint, seq: bigint, boardId: string, } | { "type": "FocusedBoardChanged", v: number, ts: bigint, seq: bigint, boardId: string, } | { "type": "ExcalidrawDelta", v: number, ts: bigint, seq: bigint, boardId: string, sceneVersion: bigint, elements: unknown[], appState: unknown, } | { "type": "ExcalidrawSceneReset", v: number, ts: bigint, seq: bigint, boardId: string, sceneVersion: bigint, elements: unknown[], appState: unknown, };

export type Topic = { id: string, parentId: string | null, title: string, ord: number, status: TopicStatus, createdAt: bigint, };

export type TopicStatus = "pending" | "done";

export type You = { clientId: string, role: Role, guestId: string, };
