// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMsg = { "type": "Hello", v: number, id: string | null, role: Role, guestId: string, displayName: string | null, adminToken: string | null, } | { "type": "SetDisplayName", v: number, id: string | null, name: string, } | { "type": "GetSnapshot", v: number, id: string | null, since: bigint | null, } | { "type": "Pong", v: number, id: string | null, } | { "type": "AddTopic", v: number, id: string | null, parentId: string | null, title: string, afterId: string | null, } | { "type": "RenameTopic", v: number, id: string | null, topicId: string, title: string, } | { "type": "MoveTopic", v: number, id: string | null, topicId: string, newParentId: string | null, afterId: string | null, } | { "type": "DeleteTopic", v: number, id: string | null, topicId: string, } | { "type": "SetActiveTopic", v: number, id: string | null, topicId: string | null, } | { "type": "MarkTopicDone", v: number, id: string | null, topicId: string, done: boolean, };

export type Guest = { guestId: string, displayName: string, muted: boolean, joinedAt: bigint, };

export type Presence = { guestId: string, displayName: string, muted: boolean, joinedAt: bigint, clientIds: Array<string>, };

export type Role = "host" | "guest";

/**
 * Welcome snapshot delivered on Hello + on every GetSnapshot. M1 carries
 * only the always-present fields; later phases populate topics/boards/etc.
 */
export type RoomSnapshot = { room: RoomSummary, you: You, guests: Array<Guest>, presence: Array<Presence>, topics: Array<Topic>, activeTopicId: string | null, questions: unknown[], myVotes: Array<string>, boards: unknown[], focusedBoardId: string | null, hands: unknown[], seq: bigint, };

export type RoomSummary = { id: string, title: string, createdAt: bigint, };

export type ServerMsg = { "type": "Welcome", v: number, ts: bigint, seq: bigint, you: You, snapshot: RoomSnapshot, } | { "type": "Error", v: number, ts: bigint, seq: bigint, code: string, message: string, refId: string | null, } | { "type": "Ack", v: number, ts: bigint, seq: bigint, refId: string, } | { "type": "PresenceUpdate", v: number, ts: bigint, seq: bigint, guests: Array<Guest>, } | { "type": "RoomSnapshot", v: number, ts: bigint, seq: bigint, snapshot: RoomSnapshot, } | { "type": "Ping", v: number, ts: bigint, seq: bigint, } | { "type": "TopicTreeUpdated", v: number, ts: bigint, seq: bigint, topics: Array<Topic>, activeTopicId: string | null, };

export type Topic = { id: string, parentId: string | null, title: string, ord: number, status: TopicStatus, createdAt: bigint, };

export type TopicStatus = "pending" | "done";

export type You = { clientId: string, role: Role, guestId: string, };
